/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectbasdat.Admin;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import projectbasdat.DatabaseTools;

/**
 *
 * @author tridi
 */
public class MainAdmin extends javax.swing.JFrame {

    DatabaseTools db = new DatabaseTools();
    ArrayList<String> daftarIdPelanggan, daftarIdKaryawan, daftarIdSupplier, daftarIdCabang, daftarIdProduk;

    public DatabaseTools getDatabaseTools() {
        return db;
    }
    
    /**
     * Creates new form Main
     */
    public MainAdmin() {
        initComponents();
        populateTableDaftarPelanggan();
        populateTableDaftarKaryawan();
        populateTableSupplier();
        populateTableCabang();
        populateTableDaftarProduk();
        
        // closing listener untuk menutup koneksi database
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                db.close();
            }
        });
        
        // listener ketika tabel daftar supplier di klik
        ListSelectionModel modelDaftarSupplier = tableDaftarSupplier.getSelectionModel();
        modelDaftarSupplier.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if (!modelDaftarSupplier.isSelectionEmpty()) {
                    int index = modelDaftarSupplier.getMinSelectionIndex();
                    String id = daftarIdSupplier.get(index);
                    populateTableDaftarProdukSupply(id);
                }
            }
        });
        
        // Listener ketika tabel daftar cabang di klik
        ListSelectionModel modelDaftarCabang = tableDaftarCabang.getSelectionModel();
        modelDaftarCabang.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if (!modelDaftarCabang.isSelectionEmpty()) {
                    int index = modelDaftarCabang.getMinSelectionIndex();
                    String id = daftarIdCabang.get(index);
                    populateTableDaftarKaryawanCabang(id);
                }
            }
        });
        
        // Listener untuk tabel daftar produk
        ListSelectionModel modelTabelDaftarProduk = tableDaftarProduk.getSelectionModel();
        modelTabelDaftarProduk.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if (!modelTabelDaftarProduk.isSelectionEmpty()) {
                    int index = modelTabelDaftarProduk.getMinSelectionIndex();
                    String id = daftarIdProduk.get(index);
                    populateDetailProduk(id);
                }
            }
        });

        
        //populateDetailProduk
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDaftarPelanggan = new javax.swing.JTable();
        buttonLihatDetailPelanggan = new javax.swing.JButton();
        buttonTambahPelanggan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDaftarKaryawan = new javax.swing.JTable();
        buttonTambahKaryawan = new javax.swing.JButton();
        buttonHapusKaryawan = new javax.swing.JButton();
        buttonEditKaryawan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDaftarSupplier = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableDaftarProdukSupply = new javax.swing.JTable();
        buttonTambahSupplier = new javax.swing.JButton();
        buttonEditDataSupplier = new javax.swing.JButton();
        buttonHapusSupplier = new javax.swing.JButton();
        buttonTambahDataSupply = new javax.swing.JButton();
        buttonHapusDataSupply = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableDaftarCabang = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableDaftarKaryawanCabang = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        buttonTambahCabang = new javax.swing.JButton();
        buttonHapusCabang = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableDaftarProduk = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNamaProduk = new javax.swing.JTextField();
        textJumlahStokProduk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textHargaProduk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        textDeskripsiProduk = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        textNutrisiProduk = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        buttonEditDetailProduk = new javax.swing.JButton();
        buttonTambahProduk = new javax.swing.JButton();
        buttonHapusProduk = new javax.swing.JButton();
        comboBoxKategori = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aplikasi Admin");

        tableDaftarPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Email", "Jenis Kelamin", "Tanggal Lahir", "Nomor HP", "Alamat", "Jumlah Order"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableDaftarPelanggan);

        buttonLihatDetailPelanggan.setText("Lihat Detail Pelanggan");

        buttonTambahPelanggan.setText("Tambah Pelanggan");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Daftar Pelanggan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonTambahPelanggan)
                                .addGap(18, 18, 18)
                                .addComponent(buttonLihatDetailPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLihatDetailPelanggan)
                    .addComponent(buttonTambahPelanggan))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pelanggan", jPanel1);

        tableDaftarKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Jenis Kelamin", "Tanggal Lahir", "Nomor HP", "Email", "Alamat", "Jabatan", "Cabang", "Gaji"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableDaftarKaryawan);

        buttonTambahKaryawan.setText("Tambah Karyawan");

        buttonHapusKaryawan.setText("Hapus Karyawan");

        buttonEditKaryawan.setText("Edit Karyawan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(buttonTambahKaryawan)
                        .addGap(18, 18, 18)
                        .addComponent(buttonHapusKaryawan)
                        .addGap(18, 18, 18)
                        .addComponent(buttonEditKaryawan))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTambahKaryawan)
                    .addComponent(buttonHapusKaryawan)
                    .addComponent(buttonEditKaryawan))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Karyawan", jPanel2);

        tableDaftarSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Alamat", "Nomor HP", "Email", "Jumlah Produk"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableDaftarSupplier);

        tableDaftarProdukSupply.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Produk", "Jumlah Di Supply", "Tanggal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableDaftarProdukSupply);

        buttonTambahSupplier.setText("Tambah Supplier");

        buttonEditDataSupplier.setText("Edit Data Supplier");

        buttonHapusSupplier.setText("Hapus Supplier");

        buttonTambahDataSupply.setText("Tambah Data Supply");

        buttonHapusDataSupply.setText("Hapus Data Supply");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(buttonTambahSupplier)
                        .addGap(18, 18, 18)
                        .addComponent(buttonEditDataSupplier)
                        .addGap(18, 18, 18)
                        .addComponent(buttonHapusSupplier)))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(buttonTambahDataSupply)
                        .addGap(18, 18, 18)
                        .addComponent(buttonHapusDataSupply))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonTambahSupplier)
                        .addComponent(buttonEditDataSupplier)
                        .addComponent(buttonHapusSupplier))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonTambahDataSupply)
                        .addComponent(buttonHapusDataSupply)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Supplier", jPanel3);

        tableDaftarCabang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Cabang", "Alamat", "Jumlah Karyawan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tableDaftarCabang);

        tableDaftarKaryawanCabang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Jabatan", "Gaji"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tableDaftarKaryawanCabang);

        jLabel9.setText("Daftar Cabang");

        jLabel10.setText("Karyawan");

        buttonTambahCabang.setText("Tambah Cabang");
        buttonTambahCabang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahCabangActionPerformed(evt);
            }
        });

        buttonHapusCabang.setText("Hapus Cabang");
        buttonHapusCabang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusCabangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(buttonTambahCabang, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonHapusCabang, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTambahCabang)
                    .addComponent(buttonHapusCabang))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cabang", jPanel5);

        tableDaftarProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Produk", "Jumlah Stok", "Harga", "Kategori"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tableDaftarProduk);
        if (tableDaftarProduk.getColumnModel().getColumnCount() > 0) {
            tableDaftarProduk.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel2.setText("Detail Produk");

        jLabel3.setText("Nama Produk");

        textNamaProduk.setEditable(false);

        textJumlahStokProduk.setEditable(false);

        jLabel4.setText("Jumlah Stok");

        jLabel5.setText("Harga");

        textHargaProduk.setEditable(false);

        jLabel6.setText("Kategori");

        jLabel7.setText("Deskripsi");

        textDeskripsiProduk.setEditable(false);
        textDeskripsiProduk.setColumns(20);
        textDeskripsiProduk.setRows(5);
        jScrollPane8.setViewportView(textDeskripsiProduk);

        textNutrisiProduk.setEditable(false);
        textNutrisiProduk.setColumns(20);
        textNutrisiProduk.setRows(5);
        jScrollPane9.setViewportView(textNutrisiProduk);

        jLabel8.setText("Nutrisi");

        buttonEditDetailProduk.setText("Edit");
        buttonEditDetailProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditDetailProdukActionPerformed(evt);
            }
        });

        buttonTambahProduk.setText("Tambah Produk");
        buttonTambahProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahProdukActionPerformed(evt);
            }
        });

        buttonHapusProduk.setText("Hapus Produk");
        buttonHapusProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusProdukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(buttonTambahProduk)
                        .addGap(18, 18, 18)
                        .addComponent(buttonHapusProduk)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(textNamaProduk))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(textJumlahStokProduk))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(textHargaProduk))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(buttonEditDetailProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane8)
                                    .addComponent(jScrollPane9)
                                    .addComponent(comboBoxKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(102, 102, 102))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textNamaProduk)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textJumlahStokProduk)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textHargaProduk)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addComponent(buttonEditDetailProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTambahProduk)
                    .addComponent(buttonHapusProduk))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Produk", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEditDetailProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditDetailProdukActionPerformed
        // TODO add your handling code here:
        if (buttonEditDetailProduk.getText().equals("Edit")) {
            textNamaProduk.setEditable(true);
            textJumlahStokProduk.setEditable(true);
            textHargaProduk.setEditable(true);
            textDeskripsiProduk.setEditable(true);
            textNutrisiProduk.setEditable(true);
            comboBoxKategori.setEditable(true);
            
            buttonEditDetailProduk.setText("Simpan");
        } else {
            textNamaProduk.setEditable(false);
            textJumlahStokProduk.setEditable(false);
            textHargaProduk.setEditable(false);
            textDeskripsiProduk.setEditable(false);
            textNutrisiProduk.setEditable(false);
            comboBoxKategori.setEditable(false);
            
            // edit recordnya
            editRecordDetailProduct();
            
            buttonEditDetailProduk.setText("Edit");
            resetDetailProduk();
            
            populateTableDaftarProduk();
        }
    }//GEN-LAST:event_buttonEditDetailProdukActionPerformed

    private void buttonTambahProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahProdukActionPerformed
        TambahProduk tp = new TambahProduk(this);
        tp.setVisible(true);
    }//GEN-LAST:event_buttonTambahProdukActionPerformed

    private void buttonHapusProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusProdukActionPerformed
        int index = tableDaftarProduk.getSelectionModel().getMinSelectionIndex();
        String id = daftarIdProduk.get(index);
        
        try {
            db.runUpdateQuery(String.format("exec delete_product %s", id));
            refresh();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menghapus: kemungkinan ada supplier atau order yang mereferensi produk ini");
        }
    }//GEN-LAST:event_buttonHapusProdukActionPerformed

    private void buttonTambahCabangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahCabangActionPerformed
        TambahCabang tc = new TambahCabang(this);
        tc.setVisible(true);
    }//GEN-LAST:event_buttonTambahCabangActionPerformed

    private void buttonHapusCabangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusCabangActionPerformed
        
    }//GEN-LAST:event_buttonHapusCabangActionPerformed

    private void resetDetailProduk() {
        textNamaProduk.setText("");
        textJumlahStokProduk.setText("");
        textHargaProduk.setText("");
        textDeskripsiProduk.setText("");
        textNutrisiProduk.setText("");
        comboBoxKategori.setSelectedItem(null);
    }
    
    private void editRecordDetailProduct() {
        String nama = textNamaProduk.getText();
        String jumlah = textJumlahStokProduk.getText();
        String harga = textHargaProduk.getText();
        String deskripsi = textDeskripsiProduk.getText();
        String nutrisi = textNutrisiProduk.getText();
        String kategori = comboBoxKategori.getSelectedItem().toString();
        
        int index = tableDaftarProduk.getSelectionModel().getMinSelectionIndex();
        String id = daftarIdProduk.get(index);
        
        try {
            String query = String.format("exec update_detail_product\n" +
            "%s, '%s', %s, %s, '%s', '%s', '%s'", id, nama, jumlah, harga, deskripsi, nutrisi, kategori);
            db.runUpdateQuery(query);
            
            JOptionPane.showMessageDialog(null, "Berhasil");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal mengupdate");
        }
    }
    
    public void refresh() {
        populateTableDaftarPelanggan();
        populateTableDaftarKaryawan();
        populateTableSupplier();
        populateTableCabang();
        populateTableDaftarProduk();
        
        resetDetailProduk();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAdmin().setVisible(true);
            }
        });
    }
    
    private void populateTableDaftarPelanggan() {
        try {
            String query = "exec get_data_pelanggan";
            ResultSet rs = db.runQuery(query);
            
            DefaultTableModel tableModel = (DefaultTableModel)tableDaftarPelanggan.getModel();
            tableModel.setRowCount(0);
            daftarIdPelanggan = new ArrayList();
            
            while (rs.next()) {
                daftarIdPelanggan.add(rs.getString("id_pelanggan"));
                tableModel.addRow(new Object[] {
                    rs.getString("nama_pelanggan"),
                    rs.getString("email"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("tanggal_lahir"),
                    rs.getString("nomor_hp"),
                    rs.getString("alamat"),
                    rs.getString("jumlah_order")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ada error mengisi table daftar Pelanggan");
        }
    }
    
    private void populateTableDaftarKaryawan() {
        try {
            String query = "exec get_data_karyawan";
            ResultSet rs = db.runQuery(query);
            
            DefaultTableModel tableModel = (DefaultTableModel)tableDaftarKaryawan.getModel();
            tableModel.setRowCount(0);
            daftarIdKaryawan = new ArrayList();
            
            while (rs.next()) {
                daftarIdKaryawan.add(rs.getString("id_karyawan"));
                tableModel.addRow(new Object[] {
                    rs.getString("nama"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("tanggal_lahir"),
                    rs.getString("nomor_hp"),
                    rs.getString("email"),
                    rs.getString("alamat"),
                    rs.getString("jabatan"),
                    rs.getString("nama_cabang"),
                    rs.getString("gaji")
                });
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ada error mengisi table daftar karyawan");
        }
    }
    
    private void populateTableSupplier() {
        try {
            String query = "exec get_data_supplier";
            ResultSet rs = db.runQuery(query);
            DefaultTableModel tableModel = (DefaultTableModel)tableDaftarSupplier.getModel();
            tableModel.setRowCount(0);
            daftarIdSupplier = new ArrayList();
            
            while (rs.next()) {
                daftarIdSupplier.add(rs.getString("id_supplier"));
                tableModel.addRow(new Object[] {
                    rs.getString("nama_supplier"),
                    rs.getString("alamat"),
                    rs.getString("nomor_hp"),
                    rs.getString("email"),
                    rs.getString("jumlah_produk")
                });
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ada error mengisi table daftar Supplier");
        }
    }
    
    private void populateTableDaftarProdukSupply(String id) {
        try {
            String query = String.format("exec get_supplied_product %s", id);
            ResultSet rs = db.runQuery(query);
            DefaultTableModel tableModel = (DefaultTableModel)tableDaftarProdukSupply.getModel();
            tableModel.setRowCount(0);
            
            while (rs.next()) {
                tableModel.addRow(new Object[] {
                    rs.getString("nama_produk"),
                    rs.getString("jumlah_produk"),
                    rs.getString("tanggal")
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ada error saat mengisi daftar produk yang disupply");
        }
    }
    
    private void populateTableDaftarKaryawanCabang(String id) {
        try {
            String query = String.format("exec get_karyawan_at_cabang %s", id);
            ResultSet rs = db.runQuery(query);
            DefaultTableModel tableModel = (DefaultTableModel)tableDaftarKaryawanCabang.getModel();
            tableModel.setRowCount(0);
            
            while (rs.next()) {
                tableModel.addRow(new Object[] {
                    rs.getString("nama"),
                    rs.getString("jabatan"),
                    rs.getString("gaji")
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ada error saat mengisi daftar produk yang disupply");
        }
    }
    
    private void populateTableCabang() {
        try {
            String query = "exec get_data_cabang";
            ResultSet rs = db.runQuery(query);
            DefaultTableModel tableModel = (DefaultTableModel)tableDaftarCabang.getModel();
            tableModel.setRowCount(0);
            daftarIdCabang = new ArrayList();
            
            while (rs.next()) {
                daftarIdCabang.add(rs.getString("id_cabang"));
                tableModel.addRow(new Object[] {
                    rs.getString("nama_cabang"),
                    rs.getString("alamat_cabang"),
                    rs.getString("jumlah_karyawan")
                });
            }


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ada error mengisi table daftar Cabang");
        }
    }
    
    private void populateTableDaftarProduk() {
        try {
            String query = "exec get_data_tabel_produk";
            ResultSet rs = db.runQuery(query);
            DefaultTableModel tableModel = (DefaultTableModel)tableDaftarProduk.getModel();
            tableModel.setRowCount(0);
            daftarIdProduk = new ArrayList();
            
            while (rs.next()) {
                daftarIdProduk.add(rs.getString("product_id"));
                tableModel.addRow(new Object[] {
                    rs.getString("nama_produk"),
                    rs.getString("jumlah_stok"),
                    rs.getString("harga_satuan"),
                    rs.getString("kategori")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ada error mengisi tabel daftar produk!");
        }
    }
    
    private void populateDetailProduk(String id) {
        try {
            String query = String.format("exec get_detail_produk %s", id);
//            System.out.println(query);
            ResultSet rs = db.runQuery(query);
            populateComboBoxKategori();
            
            rs.next();
            textNamaProduk.setText(rs.getString("nama_produk"));
            textJumlahStokProduk.setText(rs.getString("jumlah_stok"));
            textHargaProduk.setText(rs.getString("harga_satuan"));
            textDeskripsiProduk.setText(rs.getString("deskripsi"));
            textNutrisiProduk.setText(rs.getString("nutrition_facts"));
            comboBoxKategori.setSelectedItem(rs.getString("kategori"));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ada error mendapat data");
            e.printStackTrace();
        }
    }
    
    private void populateComboBoxKategori() {
        try {
            comboBoxKategori.removeAllItems();
            ResultSet rs = db.runQuery("select * from kategori");
            
            while (rs.next()) {
                comboBoxKategori.addItem(rs.getString("nama_kategori"));
            }

        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditDataSupplier;
    private javax.swing.JButton buttonEditDetailProduk;
    private javax.swing.JButton buttonEditKaryawan;
    private javax.swing.JButton buttonHapusCabang;
    private javax.swing.JButton buttonHapusDataSupply;
    private javax.swing.JButton buttonHapusKaryawan;
    private javax.swing.JButton buttonHapusProduk;
    private javax.swing.JButton buttonHapusSupplier;
    private javax.swing.JButton buttonLihatDetailPelanggan;
    private javax.swing.JButton buttonTambahCabang;
    private javax.swing.JButton buttonTambahDataSupply;
    private javax.swing.JButton buttonTambahKaryawan;
    private javax.swing.JButton buttonTambahPelanggan;
    private javax.swing.JButton buttonTambahProduk;
    private javax.swing.JButton buttonTambahSupplier;
    private javax.swing.JComboBox<String> comboBoxKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tableDaftarCabang;
    private javax.swing.JTable tableDaftarKaryawan;
    private javax.swing.JTable tableDaftarKaryawanCabang;
    private javax.swing.JTable tableDaftarPelanggan;
    private javax.swing.JTable tableDaftarProduk;
    private javax.swing.JTable tableDaftarProdukSupply;
    private javax.swing.JTable tableDaftarSupplier;
    private javax.swing.JTextArea textDeskripsiProduk;
    private javax.swing.JTextField textHargaProduk;
    private javax.swing.JTextField textJumlahStokProduk;
    private javax.swing.JTextField textNamaProduk;
    private javax.swing.JTextArea textNutrisiProduk;
    // End of variables declaration//GEN-END:variables
}
